Vehicle Data Preparation

This notebook prepares the official UK Department for Transport vehicle dataset.

The objectives are:

- Load the vehicle dataset.
- Keep only vehicles involved in collisions from 2010 onwards.
- Explore the dataset.
- Assess data quality.
- Handle missing values where necessary.
- Remove unnecessary variables.
- Save a clean dataset for the data integration stage.

Import Libraries

In [ ]:
import pandas as pd
import numpy as np

Load Dataset

Load the cleaned collision dataset and the official vehicle dataset.

Only vehicles associated with collisions from 2010 onwards are retained to ensure consistency across the project.

In [ ]:
collisions = pd.read_csv('/content/drive/MyDrive/PROYECT_1/collision_clean.csv')

In [ ]:
valid_collision_ids = set(collisions['collision_index'])

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/PROYECT_1/dft-road-casualty-statistics-vehicle-1979-latest-published-year.csv')

/tmp/ipykernel_5778/1412139341.py:1: DtypeWarning: Columns (27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/drive/MyDrive/PROYECT_1/dft-road-casualty-statistics-vehicle-1979-latest-published-year.csv')

In [ ]:
df = df[df['collision_index'].isin(valid_collision_ids)].copy()

In [ ]:
pd.set_option('display.max_columns', None)

Exploration and Data Cleaning

In [ ]:
df.head()

,collision_index,collision_year,collision_ref_no,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,vehicle_location_restricted_lane_historic,vehicle_location_restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,first_point_of_impact,vehicle_left_hand_drive,journey_purpose_of_driver_historic,journey_purpose_of_driver,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2014214000919,2014,214000919,2,9,0,18,19,1,5,0,0,8,0,0,0,0,1,1,2,2,2,34,6,998,1,2,PEUGEOT 107,-1,E01010542,0,-1
1,2014554C16552,2014,554C16552,2,9,0,9,9,7,5,0,0,8,0,0,0,0,3,1,6,6,1,46,8,998,1,3,PEUGEOT 107,-1,E01032660,0,-1
2,201442I094703,2014,42I094703,4,9,0,3,3,7,3,0,0,5,0,0,0,0,2,1,6,6,1,58,9,998,1,5,PEUGEOT 107,-1,E01021412,0,-1
3,201443W158124,2014,43W158124,1,9,0,18,19,6,2,0,0,0,0,0,0,0,1,1,6,6,2,-1,-1,998,1,7,PEUGEOT 107,-1,-1,0,-1
4,201406L082426,2014,06L082426,2,9,0,18,19,8,4,0,0,8,0,0,0,0,4,1,6,6,2,20,4,998,1,1,PEUGEOT 107,-1,E01006253,0,-1

In [ ]:
df.shape

(3457626, 32)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3457626 entries, 0 to 16081987
Data columns (total 32 columns):
 #   Column                                     Dtype
---  ------                                     -----
 0   collision_index                            object
 1   collision_year                             int64
 2   collision_ref_no                           object
 3   vehicle_reference                          int64
 4   vehicle_type                               int64
 5   towing_and_articulation                    int64
 6   vehicle_manoeuvre_historic                 int64
 7   vehicle_manoeuvre                          int64
 8   vehicle_direction_from                     int64
 9   vehicle_direction_to                       int64
 10  vehicle_location_restricted_lane_historic  int64
 11  vehicle_location_restricted_lane           int64
 12  junction_location                          int64
 13  skidding_and_overturning                   int64
 14  hit_object_in_carriageway                  int64
 15  vehicle_leaving_carriageway                int64
 16  hit_object_off_carriageway                 int64
 17  first_point_of_impact                      int64
 18  vehicle_left_hand_drive                    int64
 19  journey_purpose_of_driver_historic         int64
 20  journey_purpose_of_driver                  int64
 21  sex_of_driver                              int64
 22  age_of_driver                              int64
 23  age_band_of_driver                         int64
 24  engine_capacity_cc                         int64
 25  propulsion_code                            int64
 26  age_of_vehicle                             int64
 27  generic_make_model                         object
 28  driver_imd_decile                          int64
 29  lsoa_of_driver                             object
 30  escooter_flag                              int64
 31  driver_distance_banding                    int64
dtypes: int64(28), object(4)
memory usage: 870.5+ MB

In [ ]:
df.describe()

,collision_year,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre_historic,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,vehicle_location_restricted_lane_historic,vehicle_location_restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,first_point_of_impact,vehicle_left_hand_drive,journey_purpose_of_driver_historic,journey_purpose_of_driver,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,driver_imd_decile,escooter_flag,driver_distance_banding
count,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06,3.457626e+06
mean,2.016351e+03,1.554790e+00,9.695599e+00,1.149147e-01,1.476146e+01,1.582488e+01,4.260764e+00,4.257856e+00,2.967812e+00,3.012850e+00,2.623235e+00,4.703484e-01,3.263261e+00,5.939396e-01,3.331031e+00,1.877452e+00,1.220115e+00,5.057882e+00,4.452972e+00,1.442126e+00,3.515395e+01,5.898109e+00,1.389634e+03,9.349828e-01,5.622835e+00,1.588868e+00,1.695094e-03,-8.761905e-01
std,4.265663e+00,1.573681e+00,9.623825e+00,9.340878e-01,1.600269e+01,1.592663e+01,2.558847e+00,2.561405e+00,1.654575e+01,1.657000e+01,3.247896e+00,1.687076e+00,1.683987e+01,1.964583e+00,1.662161e+01,1.453716e+00,1.298031e+00,3.302513e+00,2.463622e+00,6.505077e-01,2.047189e+01,3.087400e+00,1.627368e+03,1.485539e+00,5.981202e+00,3.523935e+00,4.113661e-02,6.473961e-01
min,2.010000e+03,1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00,-1.000000e+00
25%,2.013000e+03,1.000000e+00,9.000000e+00,0.000000e+00,5.000000e+00,7.000000e+00,2.000000e+00,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,2.300000e+01,5.000000e+00,-1.000000e+00,1.000000e+00,0.000000e+00,-1.000000e+00,0.000000e+00,-1.000000e+00
50%,2.016000e+03,1.000000e+00,9.000000e+00,0.000000e+00,1.700000e+01,1.900000e+01,4.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,6.000000e+00,6.000000e+00,1.000000e+00,3.500000e+01,6.000000e+00,1.388000e+03,1.000000e+00,5.000000e+00,-1.000000e+00,0.000000e+00,-1.000000e+00
75%,2.020000e+03,2.000000e+00,9.000000e+00,0.000000e+00,1.800000e+01,1.900000e+01,6.000000e+00,7.000000e+00,0.000000e+00,0.000000e+00,6.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00,1.000000e+00,6.000000e+00,6.000000e+00,2.000000e+00,4.900000e+01,8.000000e+00,1.896000e+03,2.000000e+00,1.000000e+01,4.000000e+00,0.000000e+00,-1.000000e+00
max,2.024000e+03,9.990000e+02,9.900000e+01,9.000000e+00,9.900000e+01,9.900000e+01,9.000000e+00,9.000000e+00,9.900000e+01,9.900000e+01,9.000000e+00,9.000000e+00,9.900000e+01,9.000000e+00,9.900000e+01,9.000000e+00,9.000000e+00,1.500000e+01,9.000000e+00,3.000000e+00,1.020000e+02,1.100000e+01,9.999900e+04,1.200000e+01,1.230000e+02,1.000000e+01,1.000000e+00,5.000000e+00

In [ ]:
df.isnull().sum()

collision_index                              0
collision_year                               0
collision_ref_no                             0
vehicle_reference                            0
vehicle_type                                 0
towing_and_articulation                      0
vehicle_manoeuvre_historic                   0
vehicle_manoeuvre                            0
vehicle_direction_from                       0
vehicle_direction_to                         0
vehicle_location_restricted_lane_historic    0
vehicle_location_restricted_lane             0
junction_location                            0
skidding_and_overturning                     0
hit_object_in_carriageway                    0
vehicle_leaving_carriageway                  0
hit_object_off_carriageway                   0
first_point_of_impact                        0
vehicle_left_hand_drive                      0
journey_purpose_of_driver_historic           0
journey_purpose_of_driver                    0
sex_of_driver                                0
age_of_driver                                0
age_band_of_driver                           0
engine_capacity_cc                           0
propulsion_code                              0
age_of_vehicle                               0
generic_make_model                           0
driver_imd_decile                            0
lsoa_of_driver                               0
escooter_flag                                0
driver_distance_banding                      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.nunique()

collision_index                              1886746
collision_year                                    15
collision_ref_no                             1655485
vehicle_reference                                 84
vehicle_type                                      22
towing_and_articulation                            8
vehicle_manoeuvre_historic                        20
vehicle_manoeuvre                                 19
vehicle_direction_from                            11
vehicle_direction_to                              11
vehicle_location_restricted_lane_historic         12
vehicle_location_restricted_lane                   9
junction_location                                 11
skidding_and_overturning                           8
hit_object_in_carriageway                         14
vehicle_leaving_carriageway                       11
hit_object_off_carriageway                        14
first_point_of_impact                              7
vehicle_left_hand_drive                            4
journey_purpose_of_driver_historic                 8
journey_purpose_of_driver                          7
sex_of_driver                                      4
age_of_driver                                    103
age_band_of_driver                                12
engine_capacity_cc                              2482
propulsion_code                                   13
age_of_vehicle                                   111
generic_make_model                              1589
driver_imd_decile                                 11
lsoa_of_driver                                 37508
escooter_flag                                      2
driver_distance_banding                            6
dtype: int64

In [ ]:
columns_to_drop = [

    "collision_ref_no",

    "vehicle_manoeuvre_historic",

    "vehicle_location_restricted_lane_historic",

    "journey_purpose_of_driver_historic"

]

In [ ]:
df.drop(columns=columns_to_drop, inplace=True)

Save Clean Dataset

Export the cleaned vehicle dataset.

The resulting dataset will be combined with the collision and casualty datasets during the data integration stage.

In [ ]:
df.to_csv('vehicle_clean.csv', index=False)

Final Dataset

The vehicle dataset was successfully prepared for the next stage of the project.

Summary of the work completed:

- Filtered the dataset to include only vehicles involved in collisions from 2010 onwards.
- Assessed the overall quality of the data.
- Verified that no duplicate records were present.
- Confirmed that no missing values required treatment.
- Removed redundant identifier variables.
- Removed deprecated historical variables while retaining the latest coding standards.
- Exported a clean dataset ready for data integration.

In [19]:
print('Vehicle Dataset Summary')
print('='*50)
print(f'Rows: {df.shape[0]}')
print(f'Columns: {df.shape[1]}')
print(f'Missing Values: {df.isnull().sum().sum()}')
print(f'Duplicate Rows: {df.duplicated().sum()}')

Vehicle Dataset Summary
==================================================
Rows: 3457626
Columns: 28
Missing Values: 0
Duplicate Rows: 0

In [ ]:
df.head()

,collision_index,collision_year,vehicle_reference,vehicle_type,towing_and_articulation,vehicle_manoeuvre,vehicle_direction_from,vehicle_direction_to,vehicle_location_restricted_lane,junction_location,skidding_and_overturning,hit_object_in_carriageway,vehicle_leaving_carriageway,hit_object_off_carriageway,first_point_of_impact,vehicle_left_hand_drive,journey_purpose_of_driver,sex_of_driver,age_of_driver,age_band_of_driver,engine_capacity_cc,propulsion_code,age_of_vehicle,generic_make_model,driver_imd_decile,lsoa_of_driver,escooter_flag,driver_distance_banding
0,2014214000919,2014,2,9,0,19,1,5,0,8,0,0,0,0,1,1,2,2,34,6,998,1,2,PEUGEOT 107,-1,E01010542,0,-1
1,2014554C16552,2014,2,9,0,9,7,5,0,8,0,0,0,0,3,1,6,1,46,8,998,1,3,PEUGEOT 107,-1,E01032660,0,-1
2,201442I094703,2014,4,9,0,3,7,3,0,5,0,0,0,0,2,1,6,1,58,9,998,1,5,PEUGEOT 107,-1,E01021412,0,-1
3,201443W158124,2014,1,9,0,19,6,2,0,0,0,0,0,0,1,1,6,2,-1,-1,998,1,7,PEUGEOT 107,-1,-1,0,-1
4,201406L082426,2014,2,9,0,19,8,4,0,8,0,0,0,0,4,1,6,2,20,4,998,1,1,PEUGEOT 107,-1,E01006253,0,-1